#!/bin/bash

set -eu

if [ -f ./dist/bin/js ]; then
    JS=./dist/bin/js
elif git rev-parse --git-dir >/dev/null 2>&1 && [ `git rev-parse --is-inside-work-tree` == true ]; then
    SRCDIR=`git rev-parse --show-toplevel`/js/src
    OBJDIR="$SRCDIR/build_DBG.OBJ"
    JS="$OBJDIR/dist/bin/js"
else
    SRCDIR=`hg root`/js/src
    OBJDIR="$SRCDIR/build_DBG.OBJ"
    JS="$OBJDIR/dist/bin/js"
fi

exec $JS --enable-experimental-fields "$@"
