#!/bin/bash

set -eu

SRCDIR="$HOME/work/gecko/js/src"
cd "$SRCDIR"
autoconf213

BUILDDIR="$SRCDIR/build_DBG.OBJ"
rm -rf "$BUILDDIR"
mkdir "$BUILDDIR"
cd "$BUILDDIR"
../configure --enable-debug --disable-optimize --with-macos-sdk=/Users/jorendorff/work/phracker/MacOSX-SDKs/MacOSX10.14.sdk
make -j9
./dist/bin/js ../Y.js
cd ..

BUILDDIR="$SRCDIR/build_TEST.OBJ"
rm -rf "$BUILDDIR"
mkdir "$BUILDDIR"
cd "$BUILDDIR"
../configure --enable-debug --enable-optimize --with-macos-sdk=/Users/jorendorff/work/phracker/MacOSX-SDKs/MacOSX10.14.sdk
make -j9
./dist/bin/js ../Y.js
cd ..

echo "build ok"
