#!/bin/bash

set -e

if [ -f ./dist/bin/js ]; then
    OBJDIR=`pwd`
    SRCDIR=`dirname "$OBJDIR"`
elif git rev-parse --git-dir >/dev/null 2>&1 && [ `git rev-parse --is-inside-work-tree` == true ]; then
    SRCDIR=`git rev-parse --show-toplevel`/js/src
    OBJDIR=$SRCDIR/od-obj
else
    SRCDIR=`hg root`/js/src
    OBJDIR=$SRCDIR/od-obj
fi

. "$OBJDIR/_virtualenvs/init/bin/activate"

BINDIR="$OBJDIR"
if [ -d "$BINDIR/js" ]; then
    BINDIR="$BINDIR/dist/bin"
fi
JS="$BINDIR/js"

if [ $# == 0 ]; then
    "$BINDIR/jsapi-tests"
fi

cd "$SRCDIR/jit-test"
echo "running jit-test"
python jit_test.py -f --no-slow "$JS" $@ || echo "FAIL FAIL FAIL"

cd "$SRCDIR/tests"
echo "running js-tests"
python jstests.py -j8 "$JS" $@
