#!/bin/bash

set -eu

# Exuberant ctags, installed via homebrew on OS X (/usr/local/bin/ctags there)
CTAGS=ctags

JSDIR=`hg root`
cd "$JSDIR"
find js nsprpub mfbt \( -name '*-obj' -prune \) -o \( -name '*.c' -o -name '*.cpp' -o -name '*.h' \) -print | xargs $CTAGS -e
