#!/bin/bash
# rusteval: evaluate a rust expression

set -eu

cd ~/src/rust-ignorance/playground
rm -rf rusteval rusteval.rs
echo "#![allow(unused_variables, dead_code)] " > rusteval.rs
echo "fn main() { let v = {$@}; println!(\"{:?}\", v); }" >> rusteval.rs
rustc rusteval.rs
./rusteval
